version: '3.3'
services:
  db:
    image: mariadb
    volumes:
      - gfb_data:/var/lib/mysql
      - ./opt/custom.cnf:/etc/mysql/conf.d/custom.cnf
    platform: linux/amd64
    command:
      - "--plugin-load-add=ed25519"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    image: wordpress
    platform: linux/amd64
    container_name: "gfb-wordpress"
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./local/www:/var/www/html
volumes:
    gfb_data: {}
